from tkinter import *
def sum():
    int1 = int(E1.get())
    int2 = int(E2.get())
    ans.config(text=int1+int2)
def dif():
    int1 = int(E1.get())
    int2 = int(E2.get())
    ans.config(text=int1-int2)
def mul():
    int1 = int(E1.get())
    int2 = int(E2.get())
    ans.config(text=int1*int2)
def div():
    int1 = int(E1.get())
    int2 = int(E2.get())
    ans.config(text=int1/int2)
window = Tk()
E1 = Entry(window, width=5)
E1.grid(row=0,column=0)
E2 = Entry(window, width=5)
E2.grid(row=0,column=1)
plus = Button(window, text="+",bg="#008080",fg="#fff",relief=FLAT,command=sum)
minus = Button(window, text="-",bg="#008080",fg="#fff",relief=FLAT, command=dif)
multiply = Button(window, text="x",bg="#008080",fg="#fff",relief=FLAT, command=mul)
divide = Button(window, text="/",bg="#008080",fg="#fff",relief=FLAT, command=div)
plus.grid(row=1,column=0)
minus.grid(row=1,column=1)
multiply.grid(row=1,column=2)
divide.grid(row=1,column=3)
text = Label(window, text="Answer: ")
text.grid(row=2,column=0)
ans = Label(window, text="")
ans.grid(row=2,column=1)
window.mainloop()
